// Generated by gencpp from file crazy_msgs/nodeReady.msg
// DO NOT EDIT!


#ifndef CRAZY_MSGS_MESSAGE_NODEREADY_H
#define CRAZY_MSGS_MESSAGE_NODEREADY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace crazy_msgs
{
template <class ContainerAllocator>
struct nodeReady_
{
  typedef nodeReady_<ContainerAllocator> Type;

  nodeReady_()
    : header()
    , status(false)  {
    }
  nodeReady_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::crazy_msgs::nodeReady_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazy_msgs::nodeReady_<ContainerAllocator> const> ConstPtr;

}; // struct nodeReady_

typedef ::crazy_msgs::nodeReady_<std::allocator<void> > nodeReady;

typedef boost::shared_ptr< ::crazy_msgs::nodeReady > nodeReadyPtr;
typedef boost::shared_ptr< ::crazy_msgs::nodeReady const> nodeReadyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazy_msgs::nodeReady_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazy_msgs::nodeReady_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazy_msgs::nodeReady_<ContainerAllocator1> & lhs, const ::crazy_msgs::nodeReady_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazy_msgs::nodeReady_<ContainerAllocator1> & lhs, const ::crazy_msgs::nodeReady_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazy_msgs::nodeReady_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazy_msgs::nodeReady_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazy_msgs::nodeReady_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazy_msgs::nodeReady_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_msgs::nodeReady_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_msgs::nodeReady_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazy_msgs::nodeReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e7de2a1b8476cc222dc6a214a9a968";
  }

  static const char* value(const ::crazy_msgs::nodeReady_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e7de2a1b8476ccULL;
  static const uint64_t static_value2 = 0x222dc6a214a9a968ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazy_msgs::nodeReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazy_msgs/nodeReady";
  }

  static const char* value(const ::crazy_msgs::nodeReady_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazy_msgs::nodeReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::crazy_msgs::nodeReady_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazy_msgs::nodeReady_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nodeReady_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazy_msgs::nodeReady_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazy_msgs::nodeReady_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZY_MSGS_MESSAGE_NODEREADY_H
