// Generated by gencpp from file crazy_msgs/ranger.msg
// DO NOT EDIT!


#ifndef CRAZY_MSGS_MESSAGE_RANGER_H
#define CRAZY_MSGS_MESSAGE_RANGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace crazy_msgs
{
template <class ContainerAllocator>
struct ranger_
{
  typedef ranger_<ContainerAllocator> Type;

  ranger_()
    : header()
    , front(0.0)
    , back(0.0)
    , up(0.0)
    , down(0.0)
    , left(0.0)
    , right(0.0)  {
    }
  ranger_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , front(0.0)
    , back(0.0)
    , up(0.0)
    , down(0.0)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _front_type;
  _front_type front;

   typedef double _back_type;
  _back_type back;

   typedef double _up_type;
  _up_type up;

   typedef double _down_type;
  _down_type down;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::crazy_msgs::ranger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazy_msgs::ranger_<ContainerAllocator> const> ConstPtr;

}; // struct ranger_

typedef ::crazy_msgs::ranger_<std::allocator<void> > ranger;

typedef boost::shared_ptr< ::crazy_msgs::ranger > rangerPtr;
typedef boost::shared_ptr< ::crazy_msgs::ranger const> rangerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazy_msgs::ranger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazy_msgs::ranger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazy_msgs::ranger_<ContainerAllocator1> & lhs, const ::crazy_msgs::ranger_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.front == rhs.front &&
    lhs.back == rhs.back &&
    lhs.up == rhs.up &&
    lhs.down == rhs.down &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazy_msgs::ranger_<ContainerAllocator1> & lhs, const ::crazy_msgs::ranger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazy_msgs::ranger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazy_msgs::ranger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazy_msgs::ranger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazy_msgs::ranger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_msgs::ranger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazy_msgs::ranger_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazy_msgs::ranger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e02e898d8f610054d3edc7f76bbb8f8";
  }

  static const char* value(const ::crazy_msgs::ranger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e02e898d8f61005ULL;
  static const uint64_t static_value2 = 0x4d3edc7f76bbb8f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazy_msgs::ranger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazy_msgs/ranger";
  }

  static const char* value(const ::crazy_msgs::ranger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazy_msgs::ranger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 front\n"
"float64 back\n"
"float64 up\n"
"float64 down\n"
"float64 left\n"
"float64 right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::crazy_msgs::ranger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazy_msgs::ranger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.front);
      stream.next(m.back);
      stream.next(m.up);
      stream.next(m.down);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ranger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazy_msgs::ranger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazy_msgs::ranger_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "front: ";
    Printer<double>::stream(s, indent + "  ", v.front);
    s << indent << "back: ";
    Printer<double>::stream(s, indent + "  ", v.back);
    s << indent << "up: ";
    Printer<double>::stream(s, indent + "  ", v.up);
    s << indent << "down: ";
    Printer<double>::stream(s, indent + "  ", v.down);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZY_MSGS_MESSAGE_RANGER_H
